### PR TITLE
compatibility w/ Adobe ColdFusion (addresses #2, #3)

### PR DESCRIPTION
**Pull request by seancoyne**
Fixes for bugs #2 & #3

### CODE REVIEW

**Comment by seancoyne** [comment]
It didn't appear that the second `fetch` function was being used anywhere so I just commented that one out.

**Comment by justincarter** [comment]
I think the newest fetch function (possibly the second one, it's a public method) is the one that needs to stay because it’s a public lib method that can be/is used by apps. In that case the other (oldest) one needs to be renamed (guessing it’s private). I would double check this merge, it could break apps.

**Comment by seancoyne** [comment]
Both functions were public

**Comment by justincarter** [comment]
Ok, it looks like you commented out the first fetch function so this should be fine. Someone can remove it later :)

**Pull request merged**
